### ISSUE TITLE
大佬，MacAutoUpdate.conf里的proxy没有留空，多了xxxxx.conf，导致作为托管配置无法url下载

### ISSUE THREAD

**Issue by felixmmy** [chenyk1219/surge#1]
另外就是各个分流现在引用的都是节点选择，但一般使用，比如奈飞用新加坡节点，openai用美国节点，要是能在ios和mac的托管配置里把proxy group各个分流分开就更好了

**Comment by chenyk1219** [comment]
已经删了，再有问题欢迎提

**Comment by chenyk1219** [comment]
分组我再想想

**Comment by felixmmy** [comment]
> 已经删了，再有问题欢迎提

感谢回复，我现用起来：）

**Comment by chenyk1219** [comment]
嗯，随时提，看到了会第一时间响应

**Comment by felixmmy** [comment]
> 嗯，马上，看到了会第一时间响应
https://raw.githubusercontent.com/chenyk1219/surge/release/ChinaDomain.list
这条是不是失效了，其实用ASN的规则可能更准确
https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/auto-update/ruleset/ASN.China.list

**Comment by chenyk1219** [comment]
我这个是域名，在中国备案的域名，不是ip

**Comment by felixmmy** [comment]
感谢大佬的教程，真的是贼方便，我现在用的折中方案就是local的rule不引用iPhoneAutoUpdate，而是直接拷贝你的rule，这样自己就可以改分流了，还加了一条防止safari跳转app和一个paypal的规则，以及一个tutamail的分流，这样是最完美的使用你这个懒人配置的方式，毕竟auto配置众口难调

**Comment by chenyk1219** [comment]
能帮助到你就行，自己能动手是最好的了，毕竟每个人使用场景不同，gpt和奈飞已经指向美国和新加坡了，有好用的规则和想法也可以提
