### ISSUE TITLE
有条规则无法更新资源，另外大佬有gemini的分流规则吗

### ISSUE THREAD

**Issue by felixmmy** [chenyk1219/surge#2]
![008652A5-09DB-4CD9-B3BA-F4A5172DC435_L0_001_1706875614 038508_o_IMG_0119](https://github.com/chenyk1219/surge/assets/76590185/23620e6c-7b83-43d6-9661-2d5e87e7c925)

**Comment by chenyk1219** [comment]
1. 这个广告集合超过了30万条，太大了，换成了精简版 AdvertisingLite/AdvertisingLite_All_No_Resolve.list
2. gemini 没用过
