### ISSUE TITLE
刚更新的adg.list，今日头条无法打开

### ISSUE THREAD

**Issue by felixmmy** [chenyk1219/surge#3]
抓包显示是ib.snssdk.com这个被封禁了

**Comment by felixmmy** [comment]
再反馈下，换了这个list，某些app秒开，比之前顺畅多了

**Comment by chenyk1219** [comment]
<img width="601" alt="image" src="https://github.com/chenyk1219/surge/assets/150651687/6bc030af-ca60-482d-93c3-35043947a74e">

adguard是直接禁了的，我看看怎么处理

**Comment by chenyk1219** [comment]
ib.snssdk.com已经放开了，Unblocking.list一起使用，并放在adg.list的最前面

**Comment by chenyk1219** [comment]
我不用头条，但是群里其他用的人是可以正常打开的，要不你卸载重装一下试试？实在不行，我再加上

<img width="272" alt="image" src="https://github.com/chenyk1219/surge/assets/150651687/086a679e-53ec-4239-a3a3-bb6a45a3bd6c">

**Comment by chenyk1219** [comment]
特地下了今日头条app测试了一下，可以正常使用

<img width="1306" alt="image" src="https://github.com/chenyk1219/surge/assets/150651687/8901bb65-8d45-499f-bc4b-c3af330ad76b">

**Comment by felixmmy** [comment]
我昨天把ib.snssdk.com放行了才行，但是今天看了你的回复，我试着把添加的规则给删了，结果又可以了，头条这个app很迷，其他的我什么都没动
