### ISSUE TITLE
大佬，最近更新了某个版本的surge后老是会断网，不知道怎么解决

### ISSUE THREAD

**Issue by felixmmy** [chenyk1219/surge#4]
或是重启手机后也会断网，但是过了1，2分钟后就自动好了
![CBAB6EF1-FACD-46C9-B52A-118626944894_L0_001_1709871266 471433_o_FullSizeRender](https://github.com/chenyk1219/surge/assets/76590185/60123dcd-4fd8-4e97-b17d-6d34998530ff)

**Comment by chenyk1219** [comment]
看截图是本地断开了链接，应该是配置文件自动更新，或者surge断网了，看看是不是状态栏会刷新vpn图标，是不是有什么软件冲突

**Comment by felixmmy** [comment]
没有刷新vpn图标，就是surge断网，前阵子更新了某个版本后surge就会断网，比如重启手机后，或者把surge关掉再重开，就会断网，有时候过一两分钟就好了，有时候会断很久

**Comment by chenyk1219** [comment]
观察了一天，没发现这个情况，我的是商店最新版不是TF版

felixmmy ***@***.***>于2024年3月11日 周一08:00写道：
